### ISSUE TITLE
iOS: onScroll event fires multiple times while typing

### ISSUE THREAD

**Issue by robertKozik** [Expensify/react-native-live-markdown#139]
platform: iOS
commit: 617ec0ec421282452bfc3f5b2b52febc8145379

reproduction: 
1. set `maxHeight` for the input
2. Type multiple new lines so the input starts to be scrollable
3. start typing

every key stroke triggers `notifyDidScroll`

https://github.com/Expensify/react-native-live-markdown/assets/61146594/f3f5a85e-44bc-4e30-ab28-f459f645da36

**Comment by tomekzaw** [comment]
It does not emit events with `y=0` when the following lines are removed:

<img width="647" alt="Screenshot 2024-01-29 at 17 51 42" src="https://github.com/Expensify/react-native-live-markdown/assets/20516055/059ab2b7-7db8-4913-88a4-b931221bfb87">

**Comment by tomekzaw** [comment]
In fact, calling `_textView.layoutManager` is sufficient to break it.
