### ISSUE TITLE
Move height to layout effect

### ISSUE THREAD

**Issue by nandorojo** [Expensify/react-native-live-markdown#166]
https://github.com/Expensify/react-native-live-markdown/blob/348fcd2034d4599738f8a364777348f7b2e8ce82/src/MarkdownTextInput.web.tsx#L467-L474

Hey! Reviewing the web code, and I'm wondering if this should get moved to a layout effect since it's adjusting the height and you'd want to do this before painting. I'm happy to PR it if so!

**Comment by nandorojo** [comment]
The same would go for this effect:

https://github.com/Expensify/react-native-live-markdown/blob/348fcd2034d4599738f8a364777348f7b2e8ce82/src/MarkdownTextInput.web.tsx#L452-L465

I can test them out a bit to be certain

**Comment by tomekzaw** [comment]
@nandorojo Thanks for reviewing the code and suggesting the improvements, feel free to submit PRs!

cc @Skalakid, the author of web implementation

**Comment by nandorojo** [comment]
Cool.

Making a small note for SSR support:

```ts
const useClientEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect
```

**Comment by tomekzaw** [comment]
FYI There's a PR that eliminates `.web.tsx` file extension in favor of `.native.tsx` (https://github.com/Expensify/react-native-live-markdown/pull/168). Let's get it merged first so we can avoid conflicts.

**Comment by nandorojo** [comment]
Sounds good

Also, PR opened
