### ISSUE TITLE
Define mentions

### ISSUE THREAD

**Issue by nandorojo** [Expensify/react-native-live-markdown#167]
Is there a way to define the possible names which can get mentioned? Something like:

```tsx
<MarkdownTextInput 
  mentionable={['Fernando ]}
/>
```

**Comment by pleerock** [comment]
Right now it seems like only `@here` is highlighted, which is... weird. Would be great to have a control over that.

**Comment by tomekzaw** [comment]
Yes, we're working on it in https://github.com/Expensify/react-native-live-markdown/pull/439

**Comment by tomekzaw** [comment]
@nandorojo @pleerock Now that https://github.com/Expensify/react-native-live-markdown/pull/439 is merged you should be able to implement your own custom logic.

**Comment by nandorojo** [comment]
hey @tomekzaw thanks for the update. Are there docs somewhere on how this kind of logic could allow us to tag users, hashtags, etc? Or maybe an example?

**Comment by tomekzaw** [comment]
@nandorojo There's an example in the README: https://github.com/Expensify/react-native-live-markdown?tab=readme-ov-file#parsing-logic You just need to replace the logic with your code to detect mentions/hashtags.
