### ISSUE TITLE
Caret at the beginning of a line with rich text treated incorrectly

### ISSUE THREAD

**Issue by BartoszGrajdek** [Expensify/react-native-live-markdown#224]
# Description
Once cursor is placed at the beginning of a line with nested block right after the cursor browser starts providing incorrect rects. We had an investigation and it seems like it thinks that the caret is placed in a line above.

# Possible solutions
1. Wrap all text-leafs with `span`/`p` just like lexical does
2. Try switching from using `\n`

# Source
https://github.com/Expensify/react-native-live-markdown/pull/220

# Video

https://github.com/Expensify/react-native-live-markdown/assets/41169160/5d5d694d-f927-4152-8cd4-bd3fcff5335b

<details>
<summary>Useful snippet</summary>

```js
function displaySpan() {
  const selection = window.getSelection();
  const caretRect = selection.getRangeAt(0).getClientRects()[0];
  const {height, top, left} = caretRect;
  const span = document.createElement('span');
  const body = document.querySelector('#root');
  span.classList.add('test');
  span.style.width = '1px';
  span.style.position = 'fixed';
  span.style.backgroundColor = 'orangered';
  span.style.height = `${height}px`;
  span.style.top = `${top}px`;
  span.style.left = `${left}px`;
  body.appendChild(span);
}

function hideSpan() {
  const span = document.querySelector('.test');
  span?.remove();
}
```
</details>

**Comment by BartoszGrajdek** [comment]
> [!NOTE]
> It's now working much better, but there's still some refinement we could do

**Comment by tomekzaw** [comment]
@BartoszGrajdek Is this bug still current?

**Comment by BartoszGrajdek** [comment]
It's fixed now 👍🏻
