### ISSUE TITLE
Eliminate leaf text nodes on web

### ISSUE THREAD

**Issue by tomekzaw** [Expensify/react-native-live-markdown#239]
## Current Behavior
Currently we treat text that is not wrapped with markdown as a text node and line breaks as `\n`, this makes the library prone to errors related with scrolling & cursor movement.

## Expected Behavior
1. All leaf text nodes should be wrapped by an individual tag
2. We should use `<br>` instead of `\n`
3. (optional) Each new paragraph / line of text should be wrapped with `<p>` tag

**Comment by tomekzaw** [comment]
@Skalakid Is this issue still relevant?

**Comment by BartoszGrajdek** [comment]
It's finished 👍🏻

**Comment by tomekzaw** [comment]
Cool, closing then
