### ISSUE TITLE
`live-markdown` + `native-stack` + `fabric` causes incorrect layout when keyboard is open on Android

### ISSUE THREAD

**Issue by kirillzyusko** [Expensify/react-native-live-markdown#346]
### Description

If you use `@expensify/react-native-live-markdown` with `native-stack` (and new arch enabled) then input is obscured by the keyboard even if `adjustResize` is specified for `softInputMode`.

Actually I don't know if it's correct repo to open an issue or it should be opened in `@expensify/react-native-live-markdown`, because:
- `native-stack` + `TextInput` from RN -> everything is working fine
- `stack` + `live-markdown` -> everything works fine
- `stack` + `TextInput` from RN -> everything is working fine
- `native-stack` + `live-markdown` produces incorrect layout.

The reason why I open it here because if you inspect elements in layout inspector then you can notice, that next children to `Screen` has incorrect layout (and I tend to think that the problem comes from RNS, but feel free to correct me - if you think it's `live-markdown` issue, let me know and I'll re-open issue there):

<img width="802" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/22820318/f75554fd-48ca-4515-8056-f010f13b59d6">

Initially I opened issue in `react-native-screens` repository https://github.com/software-mansion/react-native-screens/issues/2124

### Steps to reproduce

- click on go to details
- set focus to input

### Snack or a link to a repository

https://github.com/kirillzyusko/native-stack-markdown-repro

### Screens version

3.31.0

### React Native version

0.73.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 3A (API 33)

### Acknowledgements

Yes

**Comment by kirillzyusko** [comment]
@tomekzaw may I ask you to look into it? We're trying to integrate `native-stack` navigator in Expensify app and it's the only one blocker that remains 😔 

At least would be good to understand if it's caused by `live-markdown` or conflict is somewhere else 👀

**Comment by tomekzaw** [comment]
Hey @kirillzyusko, thanks for submitting this issue and preparing the minimal repro.

I confirm the problem is reproducible on my end.

We will investigate this issue.

**Comment by j-piasecki** [comment]
@kirillzyusko This should be fixing the problem: https://github.com/facebook/react-native/pull/44796, but I guess you will need to use a patch for now 😞.

**Comment by kirillzyusko** [comment]
@j-piasecki interesting 🤔 Originally I discovered this problem in Expensify app and then prepared a reproduction example.

But in Expensify it looks like we already include `state` during a copy:

```c++
    childNode = parentNode.clone({
        ShadowNodeFragment::propsPlaceholder(),
        std::make_shared<ShadowNode::ListOfShared>(children),
        parentNode.getState(),
    });
```

Interesting, I'll need to allocate some more time to test everything again more carefully 👍 I'll get back to you when I have tests results. Thank you for taking a look on this issue @j-piasecki and @tomekzaw ❤️

**Comment by tomekzaw** [comment]
@kirillzyusko Did you manage to find the root cause of the issue?

**Comment by kirillzyusko** [comment]
@tomekzaw no, not yet. I'm waiting for RN 0.74 to land in Expensify and then will verify all fixes related to native-stack at once 👀

**Comment by tomekzaw** [comment]
@kirillzyusko E/App was upgraded React Native 0.75, could you please revisit this issue?

**Comment by kirillzyusko** [comment]
@tomekzaw I think @chrispader is going to check that, because he took over this task 👀

**Comment by tomekzaw** [comment]
Cool, thanks in advance!

**Comment by tomekzaw** [comment]
@chrispader Just a friendly ping, did you manage to take over this task?

**Comment by kirillzyusko** [comment]
@tomekzaw I am currently working on this task and the issue is not reproducible anymore. I think we can close this issue :)
