### ISSUE TITLE
Is it possible to get input cursor `x, y` coordinate?

### ISSUE THREAD

**Issue by ehxxn** [Expensify/react-native-live-markdown#361]

**Comment by tomekzaw** [comment]
Yes, it should be possible to extend the native code so that `onSelectionChange` event returns `selection.cursorPosition.x` and `.y` as well (on iOS) and its counterpart on Android.

**Comment by kirillzyusko** [comment]
Hey @ehxxn 

You can use https://kirillzyusko.github.io/react-native-keyboard-controller/docs/api/hooks/input/use-focused-input-handler#onselectionchange to get `x`/`y` coordinates

If you want to extend `TextInput` then you can capture its tag and compare with the tag from event:

```tsx
const CustomTextInput = (props) => {
  const ref = useRef();
  const [tag, setTag] = useState(-1);

  useEffect(() => {
    setTag(findNodeHandle(ref));
  }, []);

  useFocusedInputHandler({
    onSelectionChange: (e) => {
      "worklet";

      if (e.target === tag) {
        runOnJS(props.customPropHandler)(e);
      }
    }
  }, [tag]);

  return <TextInput ref={ref} {...props} />
}
```

You may check [example](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/example/src/screens/Examples/FocusedInputHandlers/index.tsx) app to see how it works in action 👀

**Comment by ehxxn** [comment]
Thank you very much! I'll try those solutions

**Comment by kirillzyusko** [comment]
@ehxxn if you discover, that something is not working or find any bugs - feel free to open new issue in keyboard-controller repository 🙌
