### ISSUE TITLE
CommonMark/custom parser rules support

### ISSUE THREAD

**Issue by szado** [Expensify/react-native-live-markdown#405]
Thank you for this great library. I would like to use it in project, but lack of possibility to pass own parser rules is quite a problem. Is there any milestone to add this functionality? And if exists, can I somehow get involved in its implementation?

**Comment by tomekzaw** [comment]
Hey @szado, thanks for your kind words and opening this issue.

Actually, we're currently working on it. Once complete, you will be able to implement your custom logic of parsing and formatting in JavaScript as a Reanimated worklet.

More details here: https://github.com/Expensify/react-native-live-markdown/issues/317

**Comment by tomekzaw** [comment]
Hey @szado, this should be now possible since https://github.com/Expensify/react-native-live-markdown/pull/439 has just been merged.
