### ISSUE TITLE
I encountered an error when building，Does it support expo? or how to fix

### ISSUE THREAD

**Issue by Duncan-kekkai** [Expensify/react-native-live-markdown#425]
![image](https://github.com/Expensify/react-native-live-markdown/assets/169742332/0e682f8a-e8aa-4bbd-ada4-1e26571ac5c8)

my versions:

"expo": "~49.0.21"
"react-native": "0.72.6"
"@expensify/react-native-live-markdown": "^0.1.102"

**Comment by tomekzaw** [comment]
Hi @Duncan-kekkai, thanks for opening this issue.

Currently, `react-native-live-markdown` supports only React Native 0.73.

Also, it does not work out-of-the-box in Expo Go. You will need to use Expo Prebuilds, as described [here](https://x.com/kacperkapusciak/status/1810316548982382862).

**Comment by Duncan-kekkai** [comment]
> Hi @Duncan-kekkai, thanks for opening this issue.
> 
> Currently, `react-native-live-markdown` supports only React Native 0.73.
> 
> Also, it does not work out-of-the-box in Expo Go. You will need to use Expo Prebuilds, as described [here](https://x.com/kacperkapusciak/status/1810316548982382862).

thanks,Our project does not run on expo go, it is just hosted on expo. I will try to upgrade the rn version first.

**Comment by Williamoxapay** [comment]
hi @Duncan-kekkai 
I am using   "react-native": "0.74.3"   and    "expo": "~51.0.17" 

after
`npx expo prebuild` and `npx expo run:android` I got an error

Execution failed for task ':expensify_react-native-live-markdown:compileDebugJavaWithJavac'

**Comment by AlirezaBs** [comment]
hi @Duncan-kekkai 
I am using   "react-native": "0.74.3"   and    "expo": "~51.0.17" 

after   `npx expo prebuild` and `npx expo run:android` I got an error

Execution failed for task ':expensify_react-native-live-markdown:compileDebugJavaWithJavac'

**Comment by tomekzaw** [comment]
@AlirezaBs Currently, `react-native-live-markdown` supports only React Native 0.73.

Support for React Native 0.74 will be added in https://github.com/Expensify/react-native-live-markdown/pull/358.
