### ISSUE TITLE
Cursor jumps to the end after adding a space between an emoji and a text

### ISSUE THREAD

**Issue by VickyStash** [Expensify/react-native-live-markdown#443]
## Problem
The cursor jumps to the end after adding a space between an emoji and a text in the singleline input.

## Steps to reproduce

1. Inside the singleline input enter a text with the emoji, for example `😁hello` 
2. Insert a space between `😁` and `hello`, you will see that the cursor will jump to the end of the line.

Video:

https://github.com/user-attachments/assets/2835579a-bf6a-47ab-b4f8-623c2f453bb5

## Platforms
WEB

**Comment by VickyStash** [comment]
^^ @parasharrajat

**Comment by neehhaa06** [comment]
Hello! @VickyStash :)

> I think this might help solve the issue of the problem
first capturing the cursor position using 'input.selectionStart'  before the input change occurs.

> And next, get the current value of the input field using 'input.value'

> Find the index where the space should be added by locating the last occurrence of space using 'currentValue.lastIndexOf(' ')' and adding 1 to get the position after the last space.

> Insert Space: Slice string, add space.
> Update Value: Set input to new string.
> Restore Cursor: setSelectionRange.()

**Comment by Skalakid** [comment]
Fixed in https://github.com/Expensify/react-native-live-markdown/pull/482

https://github.com/user-attachments/assets/1a36fe60-64db-4f32-8e27-7eaefbad4c6c

**Comment by Skalakid** [comment]
Fixed in https://github.com/Expensify/react-native-live-markdown/pull/482

https://github.com/user-attachments/assets/1a36fe60-64db-4f32-8e27-7eaefbad4c6c
