### ISSUE TITLE
Underline support?

### ISSUE THREAD

**Issue by sergeymild** [Expensify/react-native-live-markdown#445]
Hello, thanks for great library, i have a question does it support underline styled text? and are some method to strip all markdown syntax and leave only pure text?

**Comment by tomekzaw** [comment]
Hey @sergeymild, thanks for opening this issue!

> does it support underline styled text?

Not yet, but this will be possible in a future release.

> are some method to strip all markdown syntax and leave only pure text?

Nope, the model of this library assumes that all syntax characters are visible. If you're looking for a rich-text editor, please try react-native-aztec-view from Wordpress Mobile or something similar.
