### ISSUE TITLE
`markdownStyle` updates to `emoji.fontSize` aren't applied right away on iOS

### ISSUE THREAD

**Issue by VickyStash** [Expensify/react-native-live-markdown#448]
## Problem
The  `markdownStyles`-> `emoji` -> `fontSize` update doesn't re-render the input on **iOS**.
So any time new value is passed as emoji fontSize it's not applied right away, it works only after the input value is updated (something new got entered).

## Steps to reproduce
1. Update [App.tsx](https://github.com/Expensify/react-native-live-markdown/blob/main/example/src/App.tsx) example with the next updates:
```
// Specify default markdownStyle value
const [markdownStyle, setMarkdownStyle] = React.useState({emoji: {fontSize: 19}});

// Display markdownStyles to see how it's updated
<Text>Markdown style: {JSON.stringify(markdownStyle)}</Text>

...

// Add two buttons to update emoji font size
<Button
  title="Update emoji font size to 27"
  onPress={() =>
    setMarkdownStyle({
      emoji: {
        fontSize: 27,
      },
    })
  }
/>
<Button
  title="Update emoji font size to 19"
  onPress={() =>
    setMarkdownStyle({
      emoji: {
        fontSize: 19,
      },
    })
  }
/>
```
2. Enter a couple of emojis and some text in the input
3. Tap on buttons to update the emoji font size. See that the value inside markdownStyles is updated but it has no effect on the input. Enter a new chart to the input, the updated styles will be applied now.

https://github.com/user-attachments/assets/3b549332-cf14-40ce-9d65-8c3e302f8bbc

## Platform
iOS

**Comment by VickyStash** [comment]
^^ @parasharrajat

**Comment by VickyStash** [comment]
@tomekzaw Hi, I see you were working on the `markdownStyles` feature. Do you have the capacity to take a look at the issue or maybe you can at least share some thoughts to start with? This bug [affects](https://github.com/Expensify/App/pull/47547#issuecomment-2317741926) the enlarged emojis implementation.

**Comment by tomekzaw** [comment]
Fixed in https://github.com/Expensify/react-native-live-markdown/pull/475
