### ISSUE TITLE
Error when compiling with Expo 52 on Android

### ISSUE THREAD

**Issue by DrZoidberg09** [Expensify/react-native-live-markdown#530]
After upgrading to Expo 52, compiling of rn-live-markdown breaks on Android with the following error messages:

> /modules/java.base/java/lang/CharSequence.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi': class file for android.annotation.FlaggedApi not found

> /modules/java.base/java/util/ArrayList.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/ArrayList.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/ArrayList.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/ArrayList.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/ArrayList.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/ArrayList.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/Collections.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/Collections.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/Collections.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/Collections.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/Collections.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/List.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/List.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> error: warnings found and -Werror specified
> 
> /modules/java.base/java/lang/Double.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Character.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Character.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Float.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/lang/Math.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/SequencedCollection.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/SequencedCollection.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/SequencedCollection.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/SequencedCollection.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/SequencedCollection.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/SequencedCollection.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/SequencedCollection.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'
> 
> /modules/java.base/java/util/SequencedCollection.class: warning: Cannot find annotation method 'value()' in type 'FlaggedApi'

**Comment by tomekzaw** [comment]
Hello @DrZoidberg09, thanks for reporting this issue.

Could you please check if removing the following lines from `node_modules/react-native-live-markdown/android/build.gradle` fixes the problem?
https://github.com/Expensify/react-native-live-markdown/blob/4e4f13d744dc05685c7a0907a086e5f9616906e2/android/build.gradle#L195-L197

**Comment by DrZoidberg09** [comment]
Thank you very much for the quick reply. Unfortunately, another error occurs now:

> Execution failed for task ':app:mergeDebugNativeLibs'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
>    > 2 files found with path 'lib/arm64-v8a/libreactnative.so' from inputs:
>       - /Users/thorsten/tmp/git_tmp/easy_erp/node_modules/@expensify/react-native-live-markdown/android/build/intermediates/library_jni/debug/copyDebugJniLibsProjectOnly/jni/arm64-v8a/libreactnative.so
>       - /Users/thorsten/.gradle/caches/8.10.2/transforms/80121a83b5798be0b8f8fa5233c29f88/transformed/react-android-0.76.1-debug/jni/arm64-v8a/libreactnative.so
>      If you are using jniLibs and CMake IMPORTED targets, see
>      https://developer.android.com/r/tools/jniLibs-vs-imported-targets

**Comment by tomekzaw** [comment]
@DrZoidberg09 Please `rm -rf android/build/` inside `node_modules/@expensify/react-native-live-markdown` and try again.

**Comment by DrZoidberg09** [comment]
Unfortunately, it drops the same error.

**Comment by tomekzaw** [comment]
@DrZoidberg09 Hmm, okay, how about adding `**/libreactnative.so` to this list?
https://github.com/Expensify/react-native-live-markdown/blob/4e4f13d744dc05685c7a0907a086e5f9616906e2/android/build.gradle#L145-L155

**Comment by DrZoidberg09** [comment]
Yes. That did it! Compiles and works. Thank you!

**Comment by tomekzaw** [comment]
@DrZoidberg09 Great! I've submitted PRs #532 and #533 with the fixes.
