### ISSUE TITLE
`parseExpensiMark` requires `html-entities` package to be workletized. Please add `'worklet';` directive at the top of `node_modules/html-entities/lib/index.js` using patch-package.

### ISSUE THREAD

**Issue by Gautammer** [Expensify/react-native-live-markdown#583]
**![Screenshot_1733984722](https://github.com/user-attachments/assets/d6d84c76-daf4-4432-824b-5334284c98cb)**

`Error: [react-native-live-markdown] 'parseExpensiMark' requires 'html-entities' package to be workletized. Please add 'worklet'; directive at the top of 'node_modules/html-entities/lib/index.js' using patch-package., js engine: hermes`

**My plugin version is: 0.1.207
Please help!!**

**Comment by tomekzaw** [comment]
Hi @Gautammer, thanks for reporting this issue!

`parseExpensiMark` requires `html-entities` package to be workletized.

Please add `'worklet';` directive at the top of `node_modules/html-entities/lib/index.js` using patch-package.

**Comment by Gautammer** [comment]
Any update on this?
Thank you

**Comment by tomekzaw** [comment]
@Gautammer There's no update on this. This is not a bug. Please read the error message carefully.

You need to install `html-entities` package and then add `'worklet';` directory in the first line of `node_modules/html-entities/lib/index.js`, possibly using `patch-package`.

**Comment by xeras** [comment]
How to apply the patch? There is no readme section about this, super confusing.

**Comment by MinasFakhori** [comment]
If so, Expo Go doesn't support it; you need to use Expo Dev Client instead.

You can find the documentation [here](https://docs.expo.dev/workflow/continuous-native-generation/) as linked to in the readme. 

1. Install the dev client  - `npx expo install expo-dev-client`
2. Build a Custom Development Client Since  - ` npx expo prebuild`
3. Download the custom client : 
    a. `npx expo run:android` or `npx expo run:android` - to virtualise it 
    b. `npx expo start --dev-client` - to run it locally

**Comment by xeras** [comment]
Yeas, i use expo with the dev client. But i got the same error message. The patch of `html-entities` is not applied automatically and there is no description about doing this manually.

**Comment by erickriva** [comment]
@xeras You can make it work by:

If using `npm`:
- Install `patch-package` with `npm i patch-package`
- Set `"postinstall": "patch-package"` in `scripts` in file `package.json`
- Edit package from `node_modules` as you need
- `npx patch-package {package-name}` when you finished editing

---

If using `bun`:
- `bun patch {package-name}`
- Edit package from `node_modules` as you need
- `bun patch --commit {package-name}`

Note: `bun` will create `patchedDependencies` in `package.json` to keep track of these patches.

---

Both options will create a `patches` folder in project's root. It must be sent to Git to keep track of it.

**Comment by vineyardbovines** [comment]
for anyone else still having issues, make sure you've installed html-entities version 2.5.3 exactly, or else there is no `lib` directory.

**Comment by Anabra** [comment]
Might be a naive question, but why not just contribute the patch upstream? I can help with that, if you it'd resolve this workaround

**Comment by tomekzaw** [comment]
@Anabra Adding `'worklet';` directive in `html-entities` will no longer be needed if you enable react-native-worklets' Bundle Mode.
